### ISSUE TITLE
Add Travis CI badge in readme

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/KAPIs#2]

**Comment by themonster2015** [comment]
Hi, can I work on this?

**Comment by Michaellin250** [comment]
@themonster2015 Did you finish it? I might want to work on it as well. Did you make a pull request?

**Comment by tapaswenipathak** [comment]
@themonster2015 Sure. 

@themonster2015 @Michaellin250 I will merge who ever makes a pull request. I will create more such tickets.

**Comment by Michaellin250** [comment]
Did I fix the issue?
